theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge
plugins_dir: _plugins
baseurl: /{project_name}

title: "{project_name}"
description: "Use {project_name} from 4D"
logo: "/assets/logo.png"   # optional
show_downloads: true       # controls the download links in header
github:
  is_user_page: true
  owner_url: "https://github.com/miyako"
  repository_url: "https://github.com/miyako/{project_name}"
  is_project_page: false

exclude:
  - "vendor"
  - "resources"
  - "LICENSE"
  - "README.md"
  - "Gemfile"
  - "{project_name}/userPreferences.*"
  - "{project_name}/Libraries/*"
  - "{project_name}/Data/*"
